// Generated by CoffeeScript 2.3.2
(function() {
  module.exports = this.Person = (function() {
    var counter;

    class Person {
      constructor(name) {
        this.name = name;
        counter += 1;
      }

      talk(message) {
        var message2;
        message2 = message + ' ';
        return console.log(message2 + this.name);
      }

      static instances() {
        return console.log('there are ' + counter + ' instances');
      }

    };

    counter = 0;

    return Person;

  }).call(this);

}).call(this);

//# sourceMappingURL=person.js.map
