// Generated by CoffeeScript 2.3.2
(function() {
  this.Person = class Person {
    constructor(name) {
      this.name = name;
    }

    talk(message) {
      var message2;
      message2 = message + ' ';
      return console.log(message2 + this.name);
    }

  };

  module.exports = this.Person;

}).call(this);

//# sourceMappingURL=person.js.map
