// Generated by CoffeeScript 2.3.2
(function() {
  var Person, p2, person;

  Person = require('./person.js');

  person = new Person('James');

  p2 = new Person('Kylie');

  person.talk('Welcome to the jungle,');

  Person.instances();

}).call(this);

//# sourceMappingURL=use_person.js.map
