// Generated by CoffeeScript 2.3.2
(function() {
  var Person, person;

  Person = require('./person.js');

  person = new Person('James');

  person.talk('Welcome to the jungle,');

}).call(this);

//# sourceMappingURL=use_person.js.map
